tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-bright": "#f8f9fa",
                "outline-variant": "#c5c6d2",
                "secondary-container": "#d1e1f4",
                "inverse-primary": "#b3c5ff",
                "secondary-fixed-dim": "#b8c8da",
                "on-surface": "#191c1d",
                "on-tertiary-fixed": "#241a00",
                "error-container": "#ffdad6",
                "inverse-surface": "#2e3132",
                "primary-fixed-dim": "#b3c5ff",
                "surface-container-low": "#f3f4f5",
                error: "#ba1a1a",
                "surface-variant": "#e1e3e4",
                "surface-container": "#edeeef",
                "surface-tint": "#435b9f",
                "on-primary-fixed": "#00174a",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#d4e4f6",
                "primary-fixed": "#dbe1ff",
                "surface-container-high": "#e7e8e9",
                "tertiary-container": "#cca830",
                primary: "#00113a",
                "on-primary-container": "#758dd5",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary-fixed-variant": "#574500",
                "tertiary-fixed-dim": "#e9c349",
                "primary-container": "#002366",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#2a4386",
                "on-secondary": "#ffffff",
                "on-primary": "#ffffff",
                outline: "#757682",
                "on-tertiary-container": "#4f3e00",
                "on-surface-variant": "#444650",
                "on-secondary-container": "#556474",
                secondary: "#50606f",
                "inverse-on-surface": "#f0f1f2",
                "on-background": "#191c1d",
                "on-error-container": "#93000a",
                tertiary: "#735c00",
                "on-error": "#ffffff",
                "surface-dim": "#d9dadb",
                surface: "#f8f9fa",
                "on-secondary-fixed": "#0d1d2a",
                background: "#f8f9fa",
                "on-secondary-fixed-variant": "#394857",
                "tertiary-fixed": "#ffe088",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                sm: "12px",
                gutter: "24px",
                base: "8px",
                md: "24px",
                xs: "4px",
                lg: "48px",
                xl: "80px",
                "container-max": "1200px",
            },
            fontFamily: {
                "body-lg": ["Manrope"],
                "body-md": ["Manrope"],
                h3: ["Noto Serif"],
                "label-caps": ["Manrope"],
                h2: ["Noto Serif"],
                "body-sm": ["Manrope"],
                h1: ["Noto Serif"],
            },
            fontSize: {
                "body-lg": [
                    "18px",
                    { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
                ],
                "body-md": [
                    "16px",
                    { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
                ],
                h3: [
                    "24px",
                    { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" },
                ],
                "label-caps": [
                    "12px",
                    { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" },
                ],
                h2: [
                    "36px",
                    {
                        lineHeight: "1.3",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "body-sm": [
                    "14px",
                    {
                        lineHeight: "1.5",
                        letterSpacing: "0.01em",
                        fontWeight: "400",
                    },
                ],
                h1: [
                    "48px",
                    {
                        lineHeight: "1.2",
                        letterSpacing: "-0.02em",
                        fontWeight: "700",
                    },
                ],
            },
        },
    },
};
